# Site settings
title: My Status Website
description: A website to show the status of my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joseeden.github.io" 

theme: minimal

# Exclude specific files or directories from the site
exclude:
  # - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6

# Additional configuration options
paginate: 5
paginate_path: "/page:num/"

# Custom variables (add your own custom variables here)
status_updates:
  - date: "2024-05-31"
    status: "All systems operational."
  - date: "2024-05-30"
    status: "Minor downtime due to maintenance."
  - date: "2024-05-29"
    status: "Resolved connectivity issues."

